name: Publish Docker images

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  push_to_registry:
    name: Push ${{ matrix.name }} image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: app
            image: btcpayserver/btcpayserver-plugin-builder
            dockerfile: Dockerfile
            context: .
          - name: broker
            image: btcpayserver/btcpayserver-plugin-builder-broker
            dockerfile: Dockerfile.broker
            context: .
          - name: worker
            image: btcpayserver/btcpayserver-plugin-builder-worker
            dockerfile: Dockerfile.worker
            context: PluginBuilder
          - name: proxy
            image: btcpayserver/btcpayserver-plugin-builder-proxy
            dockerfile: Dockerfile.proxy
            context: PluginBuilder
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set env
        run: echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
